# Generated by Django 5.1.4 on 2025-01-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceuser',
            old_name='seller_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='marketplaceuser',
            old_name='seller_name',
            new_name='user_name',
        ),
    ]
