# Generated by Django 5.1.4 on 2025-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0005_alter_marketplaceuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='./No_Image_Available.jpg', null=True, upload_to='product_images/'),
        ),
    ]
