# Generated by Django 5.1.4 on 2025-02-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0009_marketplaceuser_picture_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceuser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
