# Generated by Django 5.1.4 on 2025-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0010_marketplaceuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceuser',
            name='picture',
            field=models.ImageField(blank=True, default='No_profile.png', null=True, upload_to='UserProfile/'),
        ),
    ]
