# Generated by Django 5.1.4 on 2025-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0011_alter_marketplaceuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
