# Generated by Django 5.1.4 on 2025-02-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0012_alter_wallet_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='order',
        ),
        migrations.AddField(
            model_name='wallet',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MP_user.product'),
            preserve_default=False,
        ),
    ]
