# Generated by Django 5.1.4 on 2025-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MP_user', '0013_remove_wallet_order_wallet_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceuser',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
